@extends('layouts.app', ['title' => 'Dashboard', 'heading' => 'Resumen general'])

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><p class="text-muted mb-0">Una vista clara de tu operación hoy.</p></div><a href="{{ route('movements.create') }}" class="btn btn-dark"><span class="text-warning">+</span> Registrar movimiento</a></div>
<div class="row g-3 mb-4">
    @foreach ([['Productos', number_format($stats['products']), 'productos activos', '□'], ['Stock total', number_format($stats['stock']), 'unidades en todas las sedes', '▦'], ['Stock bajo', number_format($stats['low']), 'requieren atención', '⚠'], ['Agotados', number_format($stats['empty']), 'productos sin existencias', '○']] as [$label, $value, $hint, $icon])
    <div class="col-12 col-sm-6 col-xl-3"><div class="stat-card p-3 h-100"><div class="d-flex justify-content-between align-items-start"><div><div class="stat-label">{{ $label }}</div><div class="stat-value mt-2">{{ $value }}</div></div><div class="icon-box">{{ $icon }}</div></div><div class="small text-muted mt-3">{{ $hint }}</div></div></div>
    @endforeach
</div>
<div class="row g-3">
    <div class="col-12 col-xl-8"><div class="panel p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">Actividad de inventario</h2><div class="text-muted small">Entradas y salidas de los últimos 7 días</div></div><select class="form-select form-select-sm w-auto"><option>Últimos 7 días</option><option>Últimos 30 días</option></select></div><div style="height: 285px"><canvas id="movementChart"></canvas></div></div></div>
    <div class="col-12 col-xl-4"><div class="panel p-3 p-lg-4 h-100"><h2 class="h5 mb-1">Alertas prioritarias</h2><div class="text-muted small mb-3">Requieren revisión hoy</div><div class="border-bottom py-3 d-flex justify-content-between"><div><div class="fw-semibold">Stock bajo</div><div class="small text-muted">37 productos</div></div><span class="badge badge-low rounded-pill align-self-start">Revisar</span></div><div class="border-bottom py-3 d-flex justify-content-between"><div><div class="fw-semibold">Agotados</div><div class="small text-muted">12 productos</div></div><span class="badge badge-empty rounded-pill align-self-start">Urgente</span></div><div class="py-3 d-flex justify-content-between"><div><div class="fw-semibold">Sin movimiento</div><div class="small text-muted">8 productos · 30 días</div></div><span class="badge bg-light text-dark rounded-pill align-self-start">Ver</span></div></div></div>
</div>
<div class="panel p-3 p-lg-4 mt-3"><h2 class="h5 mb-3">Últimos movimientos</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Producto</th><th>Tipo</th><th>Sede</th><th class="text-end">Cantidad</th></tr></thead><tbody>@forelse($movements->take(8) as $movement)<tr><td class="fw-semibold">{{ $movement->product->name }}</td><td><span class="badge {{ $movement->type === 'entrada' ? 'badge-normal' : 'badge-low' }}">{{ ucfirst($movement->type) }}</span></td><td>{{ $movement->branch->name }}</td><td class="text-end fw-semibold">{{ $movement->quantity }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">Aún no hay movimientos.</td></tr>@endforelse</tbody></table></div></div>
@endsection
