@extends('layouts.app', ['title' => 'Dashboard', 'heading' => 'Centro de operaciones'])
@section('content')
@php($health = $stats['products'] > 0 ? max(0, round((($stats['products'] - $stats['low'] - $stats['empty']) / $stats['products']) * 100)) : 100)
<section class="dashboard-hero mb-4">
    <div><span class="eyebrow"><i data-lucide="sparkles"></i> Panorama de hoy</span><h2>Todo tu inventario,<br><em>en una sola vista.</em></h2><p>Supervisa existencias, identifica riesgos y mantén la operación en movimiento.</p></div>
    <div class="hero-actions"><a href="{{ route('products.create') }}" class="btn btn-light"><i data-lucide="package-plus"></i> Nuevo producto</a><a href="{{ route('movements.create') }}" class="btn btn-warning"><i data-lucide="plus"></i> Registrar movimiento</a><button type="button" class="btn btn-outline-light" data-tutorial-open>Ver tutorial</button></div>
    <div class="hero-grid" aria-hidden="true"></div>
</section>
<div class="row g-3 mb-4">
@foreach ([['Productos',number_format($stats['products']),'productos activos','package','neutral'],['Stock total',number_format($stats['stock']),'unidades disponibles','boxes','success'],['Stock bajo',number_format($stats['low']),'requieren atención','triangle-alert','warning'],['Agotados',number_format($stats['empty']),'sin existencias','circle-off','danger']] as [$label,$value,$hint,$icon,$tone])
<div class="col-6 col-xl-3"><article class="stat-card stat-{{ $tone }} p-3 p-lg-4 h-100"><div class="stat-top"><span class="stat-icon"><i data-lucide="{{ $icon }}"></i></span><span class="trend-chip {{ $tone === 'danger' && $stats['empty'] > 0 ? 'trend-danger' : '' }}">{{ $tone === 'success' ? 'Disponible' : ($value == 0 ? 'Sin alertas' : 'Actual') }}</span></div><div class="stat-value mt-3">{{ $value }}</div><div class="stat-label mt-1">{{ $label }}</div><div class="stat-hint">{{ $hint }}</div></article></div>
@endforeach
</div>
<div class="row g-3">
<div class="col-12 col-xl-8"><section class="panel dashboard-panel p-3 p-lg-4 h-100"><div class="panel-heading"><div><span class="section-kicker">Rendimiento</span><h2>Flujo de inventario</h2><p>Comparativa de entradas y salidas durante la semana</p></div><select class="form-select form-select-sm w-auto" aria-label="Periodo"><option>Últimos 7 días</option><option>Últimos 30 días</option></select></div><div class="chart-wrap"><canvas id="movementChart"></canvas></div></section></div>
<div class="col-12 col-xl-4"><section class="panel health-panel p-3 p-lg-4 h-100"><div class="panel-heading"><div><span class="section-kicker">Estado general</span><h2>Salud del inventario</h2></div><a href="{{ route('reports.index') }}" class="text-link">Ver reporte <i data-lucide="arrow-up-right"></i></a></div><div class="health-score" style="--score:{{ $health }}"><div><strong>{{ $health }}%</strong><span>saludable</span></div></div><div class="health-list"><div><span><i class="dot dot-success"></i>Stock saludable</span><strong>{{ max(0,$stats['products']-$stats['low']-$stats['empty']) }}</strong></div><div><span><i class="dot dot-warning"></i>Stock bajo</span><strong>{{ $stats['low'] }}</strong></div><div><span><i class="dot dot-danger"></i>Agotados</span><strong>{{ $stats['empty'] }}</strong></div></div></section></div>
</div>
<div class="row g-3 mt-0">
<div class="col-12 col-xl-8"><section class="panel p-3 p-lg-4"><div class="panel-heading"><div><span class="section-kicker">Actividad reciente</span><h2>Últimos movimientos</h2><p>Registro actualizado de entradas y salidas</p></div><a href="{{ route('movements.index') }}" class="text-link">Ver todos <i data-lucide="arrow-right"></i></a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Producto</th><th>Tipo</th><th>Sede</th><th class="text-end">Cantidad</th></tr></thead><tbody>@forelse($movements->take(6) as $movement)<tr><td><div class="product-cell"><span class="product-avatar">{{ strtoupper(substr($movement->product->name,0,1)) }}</span><div><strong>{{ $movement->product->name }}</strong><small>Movimiento reciente</small></div></div></td><td><span class="badge {{ $movement->type === 'entrada' ? 'badge-normal' : 'badge-low' }}">{{ ucfirst($movement->type) }}</span></td><td>{{ $movement->branch->name }}</td><td class="text-end"><strong>{{ $movement->type === 'entrada' ? '+' : '-' }}{{ $movement->quantity }}</strong></td></tr>@empty<tr><td colspan="4"><div class="empty-state"><i data-lucide="inbox"></i><strong>Aún no hay movimientos</strong><span>Registra la primera entrada o salida para verla aquí.</span><a href="{{ route('movements.create') }}" class="btn btn-dark btn-sm">Registrar movimiento</a></div></td></tr>@endforelse</tbody></table></div></section></div>
<div class="col-12 col-xl-4"><section class="panel p-3 p-lg-4 quick-panel h-100"><div class="panel-heading"><div><span class="section-kicker">Atajos</span><h2>Acciones rápidas</h2><p>Lo que más utilizas, a un clic</p></div></div><div class="quick-list"><a href="{{ route('movements.create') }}"><span><i data-lucide="arrow-down-to-line"></i></span><div><strong>Registrar movimiento</strong><small>Entrada o salida de stock</small></div><i data-lucide="chevron-right"></i></a><a href="{{ route('transfers.create') }}"><span><i data-lucide="repeat-2"></i></span><div><strong>Nueva transferencia</strong><small>Mover stock entre sedes</small></div><i data-lucide="chevron-right"></i></a><a href="{{ route('reports.index') }}"><span><i data-lucide="file-chart-column"></i></span><div><strong>Generar reporte</strong><small>Exportar información</small></div><i data-lucide="chevron-right"></i></a></div></section></div>
</div>
<div class="tutorial-overlay" data-tutorial-overlay aria-hidden="true"><div class="tutorial-card"><span class="tutorial-step" data-tutorial-step>1 de 4</span><h2 data-tutorial-title>Bienvenido a LIUVA</h2><p data-tutorial-text>Aprende rápidamente a controlar el inventario.</p><div class="tutorial-actions"><button class="btn btn-light" type="button" data-tutorial-skip>Omitir</button><button class="btn btn-dark" type="button" data-tutorial-next>Comenzar</button></div></div></div>
@endsection
