import './bootstrap';
import './dashboard';
import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import Modal from 'bootstrap/js/dist/modal';
import Chart from 'chart.js/auto';
import { createIcons, LayoutDashboard, Package, ArrowDownUp, Repeat2, Shapes, Building2, Users, KeyRound, ScanSearch, ChartNoAxesCombined, X, Menu, Bell, LogOut, Search, CirclePlus, SearchX, Sparkles, PackagePlus, Plus, Boxes, TriangleAlert, CircleOff, ArrowUpRight, ArrowRight, Inbox, ArrowDownToLine, ChevronRight, FileChartColumn, Layers3, Pencil, Archive, FolderOpen, Moon, Sun } from 'lucide';

createIcons({icons:{LayoutDashboard,Package,ArrowDownUp,Repeat2,Shapes,Building2,Users,KeyRound,ScanSearch,ChartNoAxesCombined,X,Menu,Bell,LogOut,Search,CirclePlus,SearchX,Sparkles,PackagePlus,Plus,Boxes,TriangleAlert,CircleOff,ArrowUpRight,ArrowRight,Inbox,ArrowDownToLine,ChevronRight,FileChartColumn,Layers3,Pencil,Archive,FolderOpen,Moon,Sun}});
const reportProducts=document.querySelector('[data-report-products]');
const essentialProducts=['limpiatodo 1lt','lejía 1lt','detergente líquido 1lt','lavavajilla líquida 1lt','jabón líquido 400ml','saca sarro 1lt','ácido 1lt','saca grasa 750ml gatillo','saca grasa 1lt','shampoo carro 750ml gatillo','silicona llantas 750ml gatillo','silicona blanca 750ml gatillo','limpiavidrios 750ml gatillo','silicona vistony','quitamanchas 1lt','quitamanchas 650ml','desinfectante pino gel 1lt','desatorador líquido 1lt','suavizante 1lt','alcohol gel 400ml','lejía gl','limpia todo gl','suavizante gl','quitamanchas gl','lavavajilla líquida gl','desinfectante pino gl','saca sarro gl','ácido doméstico gl','limpiavidrios gl','detergente líquido gl','jabón líquido gl'];
const normalizeProductName=name=>name.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
document.querySelector('[data-report-default]')?.addEventListener('click',()=>reportProducts?.querySelectorAll('[data-product-name]').forEach(option=>{option.querySelector('input').checked=essentialProducts.includes(normalizeProductName(option.dataset.productName))}));
document.querySelector('[data-report-clear]')?.addEventListener('click',()=>reportProducts?.querySelectorAll('input[type="checkbox"]').forEach(input=>{input.checked=false}));
document.querySelector('[data-report-search]')?.addEventListener('input',event=>{const query=event.target.value.trim().toLocaleLowerCase('es');reportProducts?.querySelectorAll('[data-product-name]').forEach(option=>{option.hidden=!option.dataset.productName.includes(query)})});
const root=document.documentElement;
const themeToggle=document.querySelector('[data-theme-toggle]');
const syncThemeLabel=()=>themeToggle?.setAttribute('aria-label',root.dataset.theme==='dark'?'Activar modo claro':'Activar modo oscuro');
syncThemeLabel();themeToggle?.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('liuva-theme',root.dataset.theme);syncThemeLabel();window.dispatchEvent(new CustomEvent('themechange'))});
document.querySelector('[data-sidebar-open]')?.addEventListener('click',()=>root.classList.add('sidebar-open'));
document.querySelectorAll('[data-sidebar-close]').forEach(el=>el.addEventListener('click',()=>root.classList.remove('sidebar-open')));
document.addEventListener('keydown',e=>{if(e.key==='Escape')root.classList.remove('sidebar-open')});
document.querySelectorAll('a[href]').forEach(link=>link.addEventListener('click',e=>{const url=new URL(link.href,location.href);if(!e.defaultPrevented&&url.origin===location.origin&&!link.target&&url.href!==location.href&&!url.hash)document.body.classList.add('is-navigating')}));
window.addEventListener('pageshow',()=>document.body.classList.remove('is-navigating'));
const commandOverlay=document.querySelector('[data-command-overlay]'),commandInput=document.querySelector('[data-command-input]'),commandLinks=[...document.querySelectorAll('[data-command-list] a')],commandEmpty=document.querySelector('[data-command-empty]');let commandIndex=0;
const selectCommand=index=>{commandLinks.forEach(link=>link.classList.remove('selected'));const visible=commandLinks.filter(link=>!link.hidden);if(!visible.length)return;commandIndex=(index+visible.length)%visible.length;visible[commandIndex].classList.add('selected');visible[commandIndex].scrollIntoView({block:'nearest'})};
const openCommand=()=>{if(!commandOverlay)return;commandOverlay.classList.add('open');commandOverlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>commandInput.focus(),80);selectCommand(0)};
const closeCommand=()=>{if(!commandOverlay)return;commandOverlay.classList.remove('open');commandOverlay.setAttribute('aria-hidden','true');document.body.style.overflow='';commandInput.value='';commandLinks.forEach(link=>link.hidden=false);commandEmpty.hidden=true};
document.querySelector('[data-command-open]')?.addEventListener('click',openCommand);commandOverlay?.addEventListener('click',e=>{if(e.target===commandOverlay)closeCommand()});
commandInput?.addEventListener('input',()=>{const term=commandInput.value.toLowerCase().trim();commandLinks.forEach(link=>link.hidden=!link.textContent.toLowerCase().includes(term));commandEmpty.hidden=commandLinks.some(link=>!link.hidden);commandIndex=0;selectCommand(0)});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(!commandOverlay?.classList.contains('open'))return;if(e.key==='Escape')closeCommand();if(e.key==='ArrowDown'){e.preventDefault();selectCommand(commandIndex+1)}if(e.key==='ArrowUp'){e.preventDefault();selectCommand(commandIndex-1)}if(e.key==='Enter'){const visible=commandLinks.filter(link=>!link.hidden);if(visible[commandIndex])visible[commandIndex].click()}});
const canvas=document.querySelector('#movementChart');
if(canvas){const gradient=canvas.getContext('2d').createLinearGradient(0,0,0,280);gradient.addColorStop(0,'rgba(246,201,14,.24)');gradient.addColorStop(1,'rgba(246,201,14,0)');const chartText=()=>root.dataset.theme==='dark'?'#a9aa9f':'#66665f',chartGrid=()=>root.dataset.theme==='dark'?'#2d2f29':'#efefe8';const movementChart=new Chart(canvas,{type:'line',data:{labels:['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'],datasets:[{label:'Entradas',data:[12,19,8,15,12,18,22],borderColor:'#e4b900',backgroundColor:gradient,fill:true,tension:.4,borderWidth:2.5,pointRadius:0,pointHoverRadius:5},{label:'Salidas',data:[8,12,14,10,17,13,18],borderColor:root.dataset.theme==='dark'?'#e7e7df':'#24241f',backgroundColor:'transparent',tension:.4,borderWidth:2,pointRadius:0,pointHoverRadius:5}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:'index'},plugins:{legend:{position:'bottom',labels:{color:chartText(),usePointStyle:true,boxWidth:7,padding:22,font:{size:11}}}},scales:{x:{ticks:{color:chartText()},grid:{display:false},border:{display:false}},y:{ticks:{color:chartText()},beginAtZero:true,border:{display:false},grid:{color:chartGrid()}}}}});window.addEventListener('themechange',()=>{movementChart.data.datasets[1].borderColor=root.dataset.theme==='dark'?'#e7e7df':'#24241f';movementChart.options.plugins.legend.labels.color=chartText();movementChart.options.scales.x.ticks.color=chartText();movementChart.options.scales.y.ticks.color=chartText();movementChart.options.scales.y.grid.color=chartGrid();movementChart.update()})}
document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',()=>{if(!form.checkValidity())return;const button=form.querySelector('[data-loading-button],button[type="submit"],button:not([type])');if(button){button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Procesando...'}}));
document.querySelector('[data-whatsapp-url]')?.addEventListener('click',event=>window.open(event.currentTarget.dataset.whatsappUrl,'_blank','noopener,noreferrer'));
const tutorialOverlay=document.querySelector('[data-tutorial-overlay]');
if(tutorialOverlay){const tutorialSteps=[['#appSidebar','Menú principal','Accede a productos, movimientos, transferencias, usuarios y reportes.'],['.stat-card','Resumen del inventario','Estas tarjetas muestran el estado actual de productos, stock y alertas.'],['.quick-panel','Acciones rápidas','Registra movimientos, crea transferencias o genera reportes desde aquí.'],['.user-area','Tu cuenta','Desde esta zona puedes cambiar el tema y cerrar sesión.']];let tutorialIndex=0;const title=tutorialOverlay.querySelector('[data-tutorial-title]'),text=tutorialOverlay.querySelector('[data-tutorial-text]'),step=tutorialOverlay.querySelector('[data-tutorial-step]'),next=tutorialOverlay.querySelector('[data-tutorial-next]'),close=()=>{tutorialOverlay.classList.remove('open');tutorialOverlay.setAttribute('aria-hidden','true');document.body.style.overflow=''},render=()=>{const item=tutorialSteps[tutorialIndex];step.textContent=`${tutorialIndex+1} de ${tutorialSteps.length}`;title.textContent=item[1];text.textContent=item[2];next.textContent=tutorialIndex===tutorialSteps.length-1?'Terminar':'Siguiente'};document.querySelectorAll('[data-tutorial-open]').forEach(button=>button.addEventListener('click',()=>{tutorialIndex=0;render();tutorialOverlay.classList.add('open');tutorialOverlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));next.addEventListener('click',()=>{if(tutorialIndex===tutorialSteps.length-1){close();return}tutorialIndex++;render()});tutorialOverlay.querySelector('[data-tutorial-skip]').addEventListener('click',close)}
const scannerButton=document.querySelector('[data-barcode-scan]'),scannerVideo=document.querySelector('[data-barcode-video]'),scannerStatus=document.querySelector('[data-barcode-status]'),barcodeInput=document.querySelector('#barcode'),scannerModal=document.querySelector('#barcodeModal');
let scannerStream=null,scannerTimer=null;
if(scannerButton&&scannerVideo&&scannerModal){const modal=new Modal(scannerModal);const stopScanner=()=>{if(scannerTimer)cancelAnimationFrame(scannerTimer);if(scannerStream)scannerStream.getTracks().forEach(track=>track.stop());scannerStream=null;scannerVideo.srcObject=null};scannerButton.addEventListener('click',async()=>{if(!('BarcodeDetector' in window)){scannerStatus.textContent='Este navegador no permite escanear automáticamente. Escribe el código manualmente.';modal.show();return}try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});scannerVideo.srcObject=scannerStream;scannerStatus.textContent='Apunta la cámara al código de barras.';modal.show();const detector=new BarcodeDetector({formats:['ean_13','ean_8','code_128','upc_a','upc_e']});const scan=async()=>{if(!scannerStream)return;try{const codes=await detector.detect(scannerVideo);if(codes.length){barcodeInput.value=codes[0].rawValue;stopScanner();modal.hide();return}}catch(error){scannerStatus.textContent='No se pudo leer el código. Intenta de nuevo.'}scannerTimer=requestAnimationFrame(scan)};scannerTimer=requestAnimationFrame(scan)}catch(error){scannerStatus.textContent='No se pudo acceder a la cámara. Revisa los permisos del celular.';modal.show()}});scannerModal.addEventListener('hidden.bs.modal',stopScanner)}
document.querySelectorAll('.alert').forEach((alert,i)=>setTimeout(()=>{alert.style.cssText+='opacity:0;transform:translateY(-6px);transition:.3s';setTimeout(()=>alert.remove(),320)},5200+i*300));
