@extends('layouts.app', ['title'=>'Reportes','heading'=>'Reportes de inventario'])
@section('content')
@php
    $selectedBranch = $branches->firstWhere('id', (int) request('branch_id'));
    $whatsappMessage = $selectedBranch ? "INVENTARIO - {$selectedBranch->name}\n\n" . $inventory->sortBy(fn ($row) => $row->product->name)->map(fn ($row) => "{$row->product->name} | Cantidad: {$row->quantity} | Precio: S/ " . number_format($row->product->sale_price, 2))->implode("\n") : '';
@endphp
@if(!request('branch_id'))<div class="alert alert-warning">Selecciona una sede para consultar su inventario y sus movimientos.</div>@endif
<div class="d-flex justify-content-between mb-3"><form class="row g-2"><div class="col-auto"><select name="branch_id" class="form-select" required><option value="">Seleccionar sede</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(request('branch_id')==$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-auto"><select name="type" class="form-select"><option value="">Todos los movimientos</option><option value="entrada" @selected(request('type')==='entrada')>Entradas</option><option value="salida" @selected(request('type')==='salida')>Salidas</option></select></div><div class="col-auto"><input type="date" name="from" class="form-control" value="{{ request('from') }}"></div><div class="col-auto"><input type="date" name="to" class="form-control" value="{{ request('to') }}"></div><div class="col-auto"><button class="btn btn-outline-dark">Consultar</button></div></form><div class="d-flex gap-2">@if(request('branch_id'))<a class="btn btn-outline-dark" href="{{ route('reports.csv',request()->query()) }}">CSV</a><button class="btn btn-dark" onclick="window.print()">Imprimir PDF</button><button class="btn btn-success" data-whatsapp-url="{{ 'https://wa.me/?text=' . rawurlencode($whatsappMessage) }}">WhatsApp</button>@endif</div></div>
@if(request('branch_id'))<section class="print-report"><h1>INVENTARIO - {{ $selectedBranch?->name }}</h1><p>TIENDA IMPORTACIONES LIUVA</p><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th></tr></thead><tbody>@foreach($inventory->sortBy(fn ($row) => $row->product->name) as $row)<tr><td>{{ $row->product->name }}</td><td>{{ $row->quantity }}</td><td>S/ {{ number_format($row->product->sale_price, 2) }}</td></tr>@endforeach</tbody></table></section>@endif
@if(request('branch_id'))<div class="report-screen"><div class="row g-3"><div class="col-lg-7"><div class="panel p-3"><h2 class="h6">Existencias actuales</h2><div class="table-responsive reports-scroll"><table class="table"><thead><tr><th>Producto</th><th>Sede</th><th>Stock</th></tr></thead><tbody>@forelse($inventory as $row)<tr><td>{{ $row->product->name }}</td><td>{{ $row->branch->name }}</td><td>{{ $row->quantity }}</td></tr>@empty<tr><td colspan="3">No hay inventario para esta sede.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-5"><div class="panel p-3"><h2 class="h6">Rotación por movimientos</h2><div class="table-responsive reports-scroll"><table class="table"><thead><tr><th>Producto</th><th>Movimientos</th></tr></thead><tbody>@foreach($products->sortByDesc('movement_count') as $product)<tr><td>{{ $product->name }}</td><td>{{ $product->movement_count }}</td></tr>@endforeach</tbody></table></div></div></div></div><div class="panel p-3 mt-3"><h2 class="h6">Movimientos filtrados ({{ $movements->count() }})</h2><div class="table-responsive reports-scroll"><table class="table"><thead><tr><th>Fecha</th><th>Producto</th><th>Sede</th><th>Tipo</th><th>Cantidad</th></tr></thead><tbody>@foreach($movements as $row)<tr><td>{{ ($row->movement_date ?? $row->created_at)->format('d/m/Y') }}</td><td>{{ $row->product->name }}</td><td>{{ $row->branch->name }}</td><td>{{ ucfirst($row->type) }}</td><td>{{ $row->quantity }}</td></tr>@endforeach</tbody></table></div></div></div>@endif
@endsection
