@php($title = 'Categorías')
@php($createUrl = route('categories.create'))
@php($columns = ['Nombre', 'Slug', 'Productos', 'Estado'])
@php($values = fn($item) => [e($item->name), e($item->slug), $item->products_count, $item->is_active ? '<span class="badge badge-normal">Activa</span>' : '<span class="badge bg-secondary">Inactiva</span>'])
@php($editUrl = fn($item) => route('categories.edit', $item))
@php($deleteUrl = fn($item) => route('categories.destroy', $item))
@include('partials.crud-index')
