<?php
namespace App\Http\Controllers;
use App\Models\{Branch,Category,Inventory,InventoryMovement,Product};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class ProductController extends Controller
{
 public function index(Request $r){$allowed=$r->user()->role==='administrador'?null:$r->user()->branches()->pluck('branches.id');$branches=Branch::where('is_active',true)->when($allowed,fn($q)=>$q->whereIn('id',$allowed))->orderBy('name')->get();$items=Product::with(['category','branch','inventories.branch'])->where('is_active',true)->when($allowed,fn($q)=>$q->where(fn($q)=>$q->whereIn('branch_id',$allowed)->orWhereHas('inventories',fn($i)=>$i->whereIn('branch_id',$allowed))))->when($r->branch_id,fn($q,$v)=>$q->where(fn($q)=>$q->where('branch_id',$v)->orWhereHas('inventories',fn($i)=>$i->where('branch_id',$v))))->when($r->search,fn($q,$v)=>$q->where(fn($q)=>$q->where('name','like',"%{$v}%")->orWhere('internal_code','like',"%{$v}%")->orWhere('barcode','like',"%{$v}%")->orWhereHas('category',fn($c)=>$c->where('name','like',"%{$v}%"))))->orderBy('branch_id')->orderBy('name')->paginate(15)->withQueryString();return view('products.index',compact('items','branches'));}
 public function create(){return $this->form(new Product);} public function edit(Product $product){return $this->form($product);} private function form(Product $item){return view('products.form',['item'=>$item,'categories'=>Category::where('is_active',true)->orderBy('name')->get(),'branches'=>Branch::where('is_active',true)->orderBy('name')->get()]);}
 public function store(Request $r){return $this->save($r,new Product);} public function update(Request $r,Product $product){return $this->save($r,$product);}
 public function destroy(Product $product){$old=$product->toArray();$product->update(['is_active'=>false]);$this->audit('product.deleted',$product,$old,$product->fresh()->toArray());return back()->with('success','Producto desactivado y conservado en auditoría.');}
 public function history(Request $r,Product $product){abort_unless($r->user()->can('inventory.view')&&$r->user()->canAccessBranch((int)$product->branch_id),403);$items=$product->movements()->with(['branch','user'])->where('branch_id',$product->branch_id)->latest()->paginate(15)->withQueryString();return view('products.history',compact('product','items'));}
 private function save(Request $r,Product $product){$data=$r->validate(['branch_id'=>['required',Rule::exists('branches','id')->where('is_active',true)],'category_id'=>['required',Rule::exists('categories','id')->where('is_active',true)],'internal_code'=>['nullable','max:255',Rule::unique('products')->where(fn($q)=>$q->where('branch_id',$r->branch_id))->ignore($product->id)],'barcode'=>['nullable','max:255',Rule::unique('products')->where(fn($q)=>$q->where('branch_id',$r->branch_id))->ignore($product->id)],'name'=>'required|max:255','description'=>'nullable|string','brand'=>'nullable|max:255','sale_price'=>'required|numeric|min:0','minimum_stock'=>'required|integer|min:0','initial_quantity'=>$product->exists?'nullable':'required|integer|min:0|max:2147483647','is_active'=>'nullable|boolean']);$data['is_active']=$r->boolean('is_active',true);$data['purchase_price']=0;$old=$product->exists?$product->toArray():null;DB::transaction(function()use($r,&$product,$data,$old){if(!$product->exists&&blank($data['internal_code'])){$prefix=strtoupper(substr(Branch::findOrFail($data['branch_id'])->slug,0,4));$next=Product::where('branch_id',$data['branch_id'])->count()+1;do{$data['internal_code']=$prefix.'-'.str_pad((string)$next++,5,'0',STR_PAD_LEFT);}while(Product::where('branch_id',$data['branch_id'])->where('internal_code',$data['internal_code'])->exists());}$product->fill(collect($data)->except('initial_quantity')->all())->save();$inventory=Inventory::firstOrCreate(['product_id'=>$product->id,'branch_id'=>$data['branch_id']],['quantity'=>0]);if(!$old&&($quantity=(int)$r->input('initial_quantity',0))>0){$inventory->update(['quantity'=>$quantity,'last_entry_at'=>now()]);InventoryMovement::create(['product_id'=>$product->id,'branch_id'=>$data['branch_id'],'user_id'=>$r->user()->id,'type'=>'entrada','quantity'=>$quantity,'stock_before'=>0,'stock_after'=>$quantity,'movement_date'=>today(),'reason'=>'Stock inicial']);}});$this->audit($old?'product.updated':'product.created',$product,$old,$product->fresh()->toArray());return redirect()->route('products.index',['branch_id'=>$product->branch_id])->with('success','Producto guardado en su sede.');}
}
