<?php
namespace App\Http\Controllers;
use App\Models\{Branch,Inventory,InventoryMovement,Product};use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;use Illuminate\Support\Facades\URL;
class ReportController extends Controller
{
 private function ids(Request $r){return $r->user()->role==='administrador'?null:$r->user()->branches()->pluck('branches.id');}
 private function data(Request $r){$ids=$this->ids($r);$branches=Branch::where('is_active',true)->when($ids,fn($q)=>$q->whereIn('id',$ids))->orderBy('name')->get();if(!$r->filled('branch_id'))return compact('branches')+['inventory'=>collect(),'movements'=>collect(),'products'=>collect(),'availableProducts'=>collect(),'selectedProductIds'=>[],'selectedBranch'=>null,'shareUrl'=>null];abort_unless($branches->contains('id',(int)$r->branch_id),403);$selectedProductIds=collect($r->input('product_ids',[]))->map(fn($id)=>(int)$id)->filter()->unique()->values()->all();$availableProducts=Product::where('branch_id',$r->branch_id)->where('is_active',true)->orderBy('name')->get();$validIds=$availableProducts->pluck('id')->all();abort_if(array_diff($selectedProductIds,$validIds),403);$inventory=Inventory::with(['product.category','branch'])->where('branch_id',$r->branch_id)->when($selectedProductIds,fn($q)=>$q->whereIn('product_id',$selectedProductIds))->get();$movements=InventoryMovement::with(['product','branch'])->where('branch_id',$r->branch_id)->when($selectedProductIds,fn($q)=>$q->whereIn('product_id',$selectedProductIds))->when($r->type,fn($q,$v)=>$q->where('type',$v))->when($r->from,fn($q,$v)=>$q->whereDate('movement_date','>=',$v))->when($r->to,fn($q,$v)=>$q->whereDate('movement_date','<=',$v))->latest()->get();$products=Product::where('branch_id',$r->branch_id)->when($selectedProductIds,fn($q)=>$q->whereIn('id',$selectedProductIds))->withSum(['movements as rotation_units'=>fn($q)=>$q->where('branch_id',$r->branch_id)->where('type','salida')->when($r->from,fn($q,$v)=>$q->whereDate('movement_date','>=',$v))->when($r->to,fn($q,$v)=>$q->whereDate('movement_date','<=',$v))],'quantity')->orderByDesc('rotation_units')->get();$selectedBranch=$branches->firstWhere('id',(int)$r->branch_id);$signatureParams=['branch'=>$selectedBranch];if($selectedProductIds)$signatureParams['product_ids']=implode(',',$selectedProductIds);$shareUrl=URL::temporarySignedRoute('reports.shared',now()->addDays(7),$signatureParams);return compact('branches','inventory','movements','products','availableProducts','selectedProductIds','selectedBranch','shareUrl');}
 public function index(Request $r){abort_unless($r->user()->can('reports.view'),403);return view('reports.index',$this->data($r));}
 public function csv(Request $r){abort_unless($r->user()->can('reports.view'),403);$d=$this->data($r);abort_unless($d['selectedBranch'],422);return response()->streamDownload(function()use($d){$o=fopen('php://output','w');fputcsv($o,['Categoría','Producto','Cantidad','Precio']);foreach($d['inventory'] as $x)fputcsv($o,[$x->product->category?->name,$x->product->name,$x->quantity,$x->product->sale_price]);fclose($o);},'inventario-'.$d['selectedBranch']->slug.'.csv',['Content-Type'=>'text/csv']);}
 public function pdf(Request $r){abort_unless($r->user()->can('reports.view'),403);$d=$this->data($r);abort_unless($d['selectedBranch'],422);return Pdf::loadView('reports.pdf',$d)->setPaper('a4')->download('inventario-'.$d['selectedBranch']->slug.'.pdf');}
 public function sharedPdf(Request $r,Branch $branch){$productIds=collect(explode(',',$r->query('product_ids','')))->map(fn($id)=>(int)$id)->filter()->all();$inventory=Inventory::with(['product.category','branch'])->where('branch_id',$branch->id)->when($productIds,fn($q)=>$q->whereIn('product_id',$productIds))->get();return Pdf::loadView('reports.pdf',['inventory'=>$inventory,'selectedBranch'=>$branch])->setPaper('a4')->stream('inventario-'.$branch->slug.'.pdf');}
}
