<?php
namespace App\Http\Controllers;
use App\Models\{Branch,User};
use Illuminate\Http\Request;
class UserController extends Controller
{
 private function permissions(){return ['inventory.view'=>'Ver inventario','inventory.manage'=>'Registrar movimientos','reports.view'=>'Ver reportes'];}
 public function index(){return view('users.index',['items'=>User::with('branches')->latest()->paginate(15),'branches'=>Branch::where('is_active',true)->orderBy('name')->get(),'permissions'=>$this->permissions()]);}
 public function create(){return view('users.form',['branches'=>Branch::where('is_active',true)->orderBy('name')->get()]);}
 public function store(Request $r){$data=$r->validate(['name'=>'required|string|max:255','email'=>'required|email|unique:users,email','password'=>'required|confirmed|min:8','role'=>'required|in:administrador,vendedor','branch_id'=>'nullable|required_if:role,vendedor|exists:branches,id']);$user=User::create(['name'=>$data['name'],'email'=>$data['email'],'password'=>$data['password'],'role'=>$data['role'],'permissions'=>$data['role']==='administrador'?[]:array_keys($this->permissions())]);if($data['role']==='vendedor')$user->branches()->sync([$data['branch_id']]);$this->audit('user.created',$user,null,$user->only('name','email','role'));return redirect()->route('users.index')->with('success','Usuario creado y asignado a su tienda.');}
 public function update(Request $r,User $user){$data=$r->validate(['role'=>'required|in:administrador,vendedor','permissions'=>'array','permissions.*'=>'in:inventory.view,inventory.manage,reports.view','branch_ids'=>'array|max:1','branch_ids.*'=>'exists:branches,id']);if($data['role']==='vendedor'&&empty($data['branch_ids']))return back()->withErrors(['branch_ids'=>'Un vendedor debe pertenecer a una tienda.']);$old=['role'=>$user->role,'permissions'=>$user->permissions,'branches'=>$user->branches()->pluck('branches.id')->all()];$user->update(['role'=>$data['role'],'permissions'=>$data['role']==='administrador'?[]:($data['permissions']??[])]);$user->branches()->sync($data['role']==='administrador'?[]:$data['branch_ids']);$this->audit('user.updated',$user,$old,['role'=>$user->role,'permissions'=>$user->permissions,'branches'=>$user->branches()->pluck('branches.id')->all()]);return back()->with('success','Rol, permisos y tienda actualizados.');}
 public function toggle(Request $r,User $user){abort_if($user->is($r->user()),422,'No puedes desactivar tu propio usuario.');$old=$user->only('is_active');$user->update(['is_active'=>!$user->is_active]);$this->audit('user.status.updated',$user,$old,$user->only('is_active'));return back()->with('success','Estado actualizado.');}
 public function destroy(Request $r,User $user){abort_if($user->is($r->user()),422,'No puedes eliminar tu propio usuario.');$r->validate(['password'=>['required','current_password']]);$old=$user->only('name','email','role','is_active');$user->update(['is_active'=>false]);$user->branches()->detach();$this->audit('user.deleted',$user,$old,['is_active'=>false,'deleted'=>true]);$user->delete();return back()->with('success','Usuario eliminado y conservado en el historial.');}
}
